apiVersion: v1
kind: Secret
metadata:
  name: asset-api
  labels:
    {{- include "asset-management.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.database }}"