apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "asset-management.labels" . | nindent 4 }}
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432